export const CartActionTypes = {
	TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
	ADD_NEW_ITEM: "ADD_NEW_ITEM",
	MINUS_QUANTITY: "MINUS_QUANTITY",
	PLUS_QUANTITY: "PLUS_QUANTITY",
	DELETE_ITEM: "DELETE_ITEM",
};
